// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdEg8-D9jRQcRBkDHWwbCDPCRGIsr5KDQ',
    appId: '1:260603966127:web:cc80687cb84c58296d1a5a',
    messagingSenderId: '260603966127',
    projectId: 'helpmate-d5d6d',
    authDomain: 'helpmate-d5d6d.firebaseapp.com',
    storageBucket: 'helpmate-d5d6d.firebasestorage.app',
    measurementId: 'G-F92V0PL0PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9iX1LNLcE9Fiv5fZ1LVxHqyXHM9V5RP8',
    appId: '1:260603966127:android:4da96e0fcddf1db66d1a5a',
    messagingSenderId: '260603966127',
    projectId: 'helpmate-d5d6d',
    storageBucket: 'helpmate-d5d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC10PXxYKJ0Dnb6UBWfU42tRP8A4chDqqk',
    appId: '1:260603966127:ios:7b3143e69aef8f376d1a5a',
    messagingSenderId: '260603966127',
    projectId: 'helpmate-d5d6d',
    storageBucket: 'helpmate-d5d6d.firebasestorage.app',
    iosBundleId: 'com.example.helpMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC10PXxYKJ0Dnb6UBWfU42tRP8A4chDqqk',
    appId: '1:260603966127:ios:7b3143e69aef8f376d1a5a',
    messagingSenderId: '260603966127',
    projectId: 'helpmate-d5d6d',
    storageBucket: 'helpmate-d5d6d.firebasestorage.app',
    iosBundleId: 'com.example.helpMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdEg8-D9jRQcRBkDHWwbCDPCRGIsr5KDQ',
    appId: '1:260603966127:web:393583b4905afa996d1a5a',
    messagingSenderId: '260603966127',
    projectId: 'helpmate-d5d6d',
    authDomain: 'helpmate-d5d6d.firebaseapp.com',
    storageBucket: 'helpmate-d5d6d.firebasestorage.app',
    measurementId: 'G-040VB2EXWM',
  );

}